export const ROUTE_PATTERNS = {
  home: "/",
  login: "/login",
  setup: "/setup",
  accessDenied: "/access-denied",
  dashboard: "/dashboard",
  caseFiles: "/case-files",
  caseFile: "/case-files/:caseId",
  filingDeskQueue: "/filing-desk/queue",
  filingDeskNew: "/filing-desk/new",
  filingDeskCaseLookup: "/filing-desk/case-lookup",
  filingDeskCase: "/filing-desk/cases/:caseId",
  preparationQueue: "/preparation/queue",
  preparationCompleted: "/preparation/completed",
  preparationCase: "/preparation/cases/:caseId",
  scrutinyQueue: "/scrutiny/queue",
  scrutinyCase: "/scrutiny/cases/:caseId",
  defectCureQueue: "/defect-cure/queue",
  defectCureCase: "/defect-cure/cases/:caseId",
  defectCureCaseEdit: "/defect-cure/cases/:caseId/edit",
  scanningCaseLookup: "/scanning/case-lookup",
  scanningCompleted: "/scanning/completed",
  scanningCase: "/scanning/cases/:id",
  adminStaff: "/admin/staff",
  adminRoles: "/admin/roles",
  adminSettings: "/admin/settings",
  adminChecklists: "/admin/checklists",
  audit: "/audit",
  myPermissions: "/my-permissions",
} as const;

function p(pattern: string, params: Record<string, string>) {
  return Object.entries(params).reduce((s, [k, v]) => s.replace(`:${k}`, encodeURIComponent(v)), pattern);
}

export const routes = {
  home: () => "/",
  login: () => "/login",
  setup: () => "/setup",
  accessDenied: () => "/access-denied",
  dashboard: () => "/dashboard",
  caseFiles: () => "/case-files",
  caseFile: (caseId: string) => p("/case-files/:caseId", { caseId }),
  filingDeskQueue: () => "/filing-desk/queue",
  filingDeskNew: () => "/filing-desk/new",
  filingDeskCaseLookup: () => "/filing-desk/case-lookup",
  filingDeskCase: (caseId: string) => p("/filing-desk/cases/:caseId", { caseId }),
  preparationQueue: () => "/preparation/queue",
  preparationCompleted: () => "/preparation/completed",
  preparationCase: (caseId: string) => p("/preparation/cases/:caseId", { caseId }),
  scrutinyQueue: () => "/scrutiny/queue",
  scrutinyCase: (caseId: string) => p("/scrutiny/cases/:caseId", { caseId }),
  defectCureQueue: () => "/defect-cure/queue",
  defectCureCase: (caseId: string) => p("/defect-cure/cases/:caseId", { caseId }),
  defectCureCaseEdit: (caseId: string) => p("/defect-cure/cases/:caseId/edit", { caseId }),
  scanningCaseLookup: () => "/scanning/case-lookup",
  scanningCompleted: () => "/scanning/completed",
  scanningCase: (id: string) => p("/scanning/cases/:id", { id }),
  adminStaff: () => "/admin/staff",
  adminRoles: () => "/admin/roles",
  adminSettings: () => "/admin/settings",
  adminChecklists: () => "/admin/checklists",
  audit: () => "/audit",
  myPermissions: () => "/my-permissions",
};

export const ROUTE_PREFIXES = {
  caseFile: "/case-files/",
  filingDeskCase: "/filing-desk/cases/",
  preparationCase: "/preparation/cases/",
  scrutinyCase: "/scrutiny/cases/",
  defectCureCase: "/defect-cure/cases/",
  scanningCase: "/scanning/cases/",
} as const;
