import type { Filing, StaffMember, RoleDefinition, AuditEntry, ChecklistItem, CourtSettings } from './types';

export const MOCK_FILINGS: Filing[] = [
  {
    id: 'D-WP(C)/4688/2026',
    filing_number: 'D-WP(C)/4688/2026',
    cnr: 'ORHC01-000688-2026',
    case_category: 'Writ Petition (Civil)',
    case_type: 'petition',
    cis_state: 'registered',
    internal_stage: null,
    filing_state: 'registered_case',
    parties: [
      { name: 'Ramesh Kumar Panda', party_type: 'petitioner', address: 'Vill. Raipur, Dist. Khordha, Odisha' },
      { name: 'State of Odisha & Ors.', party_type: 'respondent', address: 'Secretariat, Bhubaneswar' },
    ],
    advocate: { name: 'Adv. Suresh Mohanty', bar_enrollment: 'OHC/1234/2010', phone: '9876543210' },
    sections: [
      { id: 's1', title: 'Docket', pages: 2, order: 1 },
      { id: 's2', title: 'Index', pages: 1, order: 2 },
      { id: 's3', title: 'Writ Petition', pages: 12, order: 3 },
      { id: 's4', title: 'Annexure A', pages: 4, order: 4 },
      { id: 's5', title: 'Annexure B', pages: 3, order: 5 },
    ],
    defects: [],
    submitted_at: '2026-03-10T09:15:00Z',
    registered_at: '2026-03-12T11:30:00Z',
    pdf_url: '/sample-docs/sample.pdf',
  },
  {
    id: 'D-WP(C)/4689/2026',
    filing_number: 'D-WP(C)/4689/2026',
    cnr: 'ORHC01-000689-2026',
    case_category: 'Writ Petition (Civil)',
    case_type: 'petition',
    cis_state: 'filed',
    internal_stage: 'defect_cure',
    filing_state: 'defects_noted',
    parties: [
      { name: 'Biswa Nath Sahoo', party_type: 'petitioner', address: 'Plot No. 45, Unit-9, Bhubaneswar' },
      { name: 'Union of India & Anr.', party_type: 'respondent', address: 'Central Govt. Offices, BBSR' },
    ],
    advocate: { name: 'Adv. Priya Mishra', bar_enrollment: 'OHC/2345/2015', phone: '9876543211' },
    sections: [
      { id: 's1', title: 'Docket', pages: 2, order: 1 },
      { id: 's2', title: 'Index', pages: 1, order: 2 },
      { id: 's3', title: 'Writ Petition', pages: 8, order: 3 },
      { id: 's4', title: 'Annexure A', pages: 5, order: 4 },
    ],
    defects: [
      { id: 'd1', code: 'D-07', description: 'Affidavit not sworn before a Notary / Oath Commissioner', resolved: false },
      { id: 'd2', code: 'D-14', description: 'Court fee stamp not affixed / insufficient court fee', resolved: false },
    ],
    submitted_at: '2026-03-14T10:00:00Z',
    defect_cure_deadline: '2026-03-19T23:59:59Z',
    defect_cure_day: 3,
    pdf_url: '/sample-docs/sample.pdf',
    assigned_to: 'officer.defect',
  },
  {
    id: 'D-WP(C)/4690/2026',
    filing_number: 'D-WP(C)/4690/2026',
    cnr: 'ORHC01-000690-2026',
    case_category: 'Writ Petition (Civil)',
    case_type: 'petition',
    cis_state: 'filed',
    internal_stage: 'scrutiny',
    filing_state: 'scrutiny',
    parties: [
      { name: 'Laxmi Devi Patnaik', party_type: 'petitioner', address: 'At/Po. Jatni, Khordha' },
      { name: 'Odisha Public Service Commission', party_type: 'respondent', address: 'OPSC, Barrack Square, BBSR' },
    ],
    advocate: { name: 'Adv. Rajesh Choudhury', bar_enrollment: 'OHC/3456/2012', phone: '9876543212' },
    sections: [
      { id: 's1', title: 'Docket', pages: 2, order: 1 },
      { id: 's2', title: 'Index', pages: 1, order: 2 },
      { id: 's3', title: 'Writ Petition', pages: 15, order: 3 },
      { id: 's4', title: 'Annexure A', pages: 6, order: 4 },
      { id: 's5', title: 'Annexure B', pages: 4, order: 5 },
      { id: 's6', title: 'Annexure C', pages: 3, order: 6 },
    ],
    defects: [],
    submitted_at: '2026-03-15T11:30:00Z',
    pdf_url: '/sample-docs/sample.pdf',
    assigned_to: 'officer.scrutiny',
  },
  {
    id: 'D-CRL(A)/0124/2026',
    filing_number: 'D-CRL(A)/0124/2026',
    cnr: 'ORHC01-000124-2026',
    case_category: 'Criminal Appeal',
    case_type: 'appeal',
    cis_state: 'filed',
    internal_stage: 'preparation',
    filing_state: 'preparation',
    parties: [
      { name: 'Mahesh Nayak', party_type: 'petitioner', address: 'Central Jail, BBSR' },
      { name: 'State of Odisha', party_type: 'respondent', address: 'Home Dept., Secretariat' },
    ],
    advocate: { name: 'Adv. Sanjay Das', bar_enrollment: 'OHC/4567/2008', phone: '9876543213' },
    sections: [
      { id: 's1', title: 'Docket', pages: 2, order: 1 },
      { id: 's2', title: 'Index', pages: 1, order: 2 },
      { id: 's3', title: 'Criminal Appeal Memo', pages: 10, order: 3 },
      { id: 's4', title: 'Trial Court Judgment', pages: 8, order: 4 },
    ],
    defects: [],
    submitted_at: '2026-03-16T09:00:00Z',
    pdf_url: '/sample-docs/sample.pdf',
    assigned_to: 'officer.preparation',
  },
  {
    id: 'D-CRL(A)/0125/2026',
    filing_number: 'D-CRL(A)/0125/2026',
    cnr: 'ORHC01-000125-2026',
    case_category: 'Criminal Appeal',
    case_type: 'appeal',
    cis_state: 'filed',
    internal_stage: 'preparation',
    filing_state: 'preparation',
    parties: [
      { name: 'Sunil Behera', party_type: 'petitioner', address: 'Vill. Kanjiamangala, Cuttack' },
      { name: 'State of Odisha', party_type: 'respondent', address: 'Home Dept., Secretariat' },
    ],
    advocate: { name: 'Adv. Meena Kar', bar_enrollment: 'OHC/5678/2018', phone: '9876543214' },
    sections: [
      { id: 's1', title: 'Docket', pages: 2, order: 1 },
      { id: 's2', title: 'Index', pages: 1, order: 2 },
      { id: 's3', title: 'Criminal Appeal Memo', pages: 7, order: 3 },
    ],
    defects: [],
    submitted_at: '2026-03-16T14:00:00Z',
    pdf_url: '/sample-docs/sample.pdf',
    assigned_to: 'officer.preparation',
  },
  {
    id: 'D-WPC(TAB)/0210/2026',
    case_category: 'Writ Petition (Civil) – Tablet',
    case_type: 'petition',
    cis_state: 'draft',
    internal_stage: 'filing',
    filing_state: 'draft',
    parties: [
      { name: 'Arun Kumar Rout', party_type: 'petitioner' },
      { name: 'State of Odisha & Ors.', party_type: 'respondent' },
    ],
    advocate: { name: 'Adv. Pramila Swain', bar_enrollment: 'OHC/6789/2020', phone: '9876543215' },
    sections: [],
    defects: [],
    submitted_at: '2026-03-20T10:00:00Z',
    pdf_url: '/sample-docs/sample.pdf',
  },
  {
    id: 'D-WPC(TAB)/0211/2026',
    filing_number: 'D-WPC(TAB)/0211/2026',
    cnr: 'ORHC01-000211-2026',
    case_category: 'Writ Petition (Civil) – Tablet',
    case_type: 'petition',
    cis_state: 'filed',
    internal_stage: 'scanning',
    filing_state: 'scanning',
    parties: [
      { name: 'Nirmal Mahapatra', party_type: 'petitioner' },
      { name: 'Registrar, Odisha High Court', party_type: 'respondent' },
    ],
    advocate: { name: 'Adv. Dilip Tripathy', bar_enrollment: 'OHC/7890/2019', phone: '9876543216' },
    sections: [],
    defects: [],
    submitted_at: '2026-03-18T08:30:00Z',
    assigned_to: 'officer.scanning',
    pdf_url: '/sample-docs/sample.pdf',
  },
  {
    id: 'D-WPC(TAB)/0212/2026',
    filing_number: 'D-WPC(TAB)/0212/2026',
    cnr: 'ORHC01-000212-2026',
    case_category: 'Writ Petition (Civil) – Tablet',
    case_type: 'petition',
    cis_state: 'filed',
    internal_stage: 'scrutiny',
    filing_state: 'scrutiny',
    parties: [
      { name: 'Anita Sahoo', party_type: 'petitioner' },
      { name: 'Odisha State Electricity Board', party_type: 'respondent' },
    ],
    advocate: { name: 'Adv. Bijay Kumar', bar_enrollment: 'OHC/8901/2016', phone: '9876543217' },
    sections: [
      { id: 's1', title: 'Docket', pages: 2, order: 1 },
      { id: 's2', title: 'Index', pages: 1, order: 2 },
      { id: 's3', title: 'Writ Petition', pages: 11, order: 3 },
    ],
    defects: [],
    submitted_at: '2026-03-19T09:45:00Z',
    assigned_to: 'officer.scrutiny',
    pdf_url: '/sample-docs/sample.pdf',
  },
  {
    id: 'D-CRL(P)/0045/2026',
    filing_number: 'D-CRL(P)/0045/2026',
    cnr: 'ORHC01-000045-2026',
    case_category: 'Criminal Petition',
    case_type: 'petition',
    cis_state: 'filed',
    internal_stage: 'defect_cure',
    filing_state: 'defects_noted',
    parties: [
      { name: 'Govinda Rath', party_type: 'petitioner' },
      { name: 'State of Odisha', party_type: 'respondent' },
    ],
    advocate: { name: 'Adv. Rashmi Pradhan', bar_enrollment: 'OHC/9012/2014', phone: '9876543218' },
    sections: [
      { id: 's1', title: 'Docket', pages: 2, order: 1 },
      { id: 's2', title: 'Index', pages: 1, order: 2 },
      { id: 's3', title: 'Criminal Petition', pages: 9, order: 3 },
      { id: 's4', title: 'FIR Copy', pages: 3, order: 4 },
    ],
    defects: [
      { id: 'd3', code: 'D-02', description: 'Advocate enrollment certificate not attached', resolved: false },
    ],
    submitted_at: '2026-03-17T13:00:00Z',
    defect_cure_deadline: '2026-03-22T23:59:59Z',
    defect_cure_day: 1,
    pdf_url: '/sample-docs/sample.pdf',
    assigned_to: 'officer.defect',
  },
  {
    id: 'D-PIL/0031/2026',
    filing_number: 'D-PIL/0031/2026',
    case_category: 'Public Interest Litigation',
    case_type: 'petition',
    cis_state: 'filed',
    internal_stage: null,
    filing_state: 'rejected',
    parties: [
      { name: 'Citizens Forum for Rights', party_type: 'petitioner' },
      { name: 'State of Odisha & Anr.', party_type: 'respondent' },
    ],
    advocate: { name: 'Adv. Kiran Jena', bar_enrollment: 'OHC/0123/2017', phone: '9876543219' },
    sections: [
      { id: 's1', title: 'Docket', pages: 2, order: 1 },
      { id: 's2', title: 'PIL Petition', pages: 20, order: 2 },
    ],
    defects: [
      { id: 'd4', code: 'D-31', description: 'Multiple defects not cured within stipulated time', resolved: false },
    ],
    submitted_at: '2026-03-13T15:00:00Z',
    pdf_url: '/sample-docs/sample.pdf',
  },
];

export const MOCK_STAFF: StaffMember[] = [
  { id: 'superadmin-1', name: 'Vyshnav Superadmin', email: 'vyshnav.superadmin@court.in', role: 'superadmin', active: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'registrar-1', name: 'Vyshnav Registrar', email: 'vyshnav.registrar@court.in', role: 'registrar', active: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'filing-1', name: 'Vyshnav Filing', email: 'vyshnav.filing@court.in', role: 'filing_officer', active: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'preparation-1', name: 'Vyshnav Preparation', email: 'vyshnav.preparation@court.in', role: 'preparation_officer', active: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'scrutiny-1', name: 'Vyshnav Scrutiny', email: 'vyshnav.scrutiny@court.in', role: 'scrutiny_officer', active: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'defect-1', name: 'Vyshnav Defect', email: 'vyshnav.defect@court.in', role: 'defect_officer', active: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'scanning-1', name: 'Vyshnav Scanning', email: 'vyshnav.scanning@court.in', role: 'scanning_officer', active: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'staff-8', name: 'Ananya Mishra', email: 'ananya.mishra@court.in', role: 'filing_officer', active: true, created_at: '2026-01-15T00:00:00Z' },
  { id: 'staff-9', name: 'Rajan Patnaik', email: 'rajan.patnaik@court.in', role: 'scrutiny_officer', active: true, created_at: '2026-01-15T00:00:00Z' },
  { id: 'staff-10', name: 'Sunita Jena', email: 'sunita.jena@court.in', role: 'preparation_officer', active: false, created_at: '2026-02-01T00:00:00Z' },
];

export const MOCK_ROLES: RoleDefinition[] = [
  {
    id: 'superadmin',
    name: 'superadmin',
    display_name: 'Superadmin',
    permissions: ['any:view_metadata', 'any:view_case_file', 'any:docs_received', 'any:case_lookup', 'system:manage_staff', 'system:view_audit', 'system:manage_court_config', 'filing:create', 'preparation:edit', 'preparation:submit', 'scrutiny:checklist', 'scrutiny:approve', 'scrutiny:reject', 'scrutiny:note_defects', 'defect:edit_case_file', 'defect:mark_removed', 'defect:return', 'defect:reject', 'scanning:upload_pdf'],
    stage_access: ['filing', 'preparation', 'scrutiny', 'defect_cure', 'scanning'],
  },
  {
    id: 'registrar',
    name: 'registrar',
    display_name: 'Registrar / Admin',
    permissions: ['any:view_metadata', 'any:view_case_file', 'any:docs_received', 'any:case_lookup', 'system:manage_staff', 'system:view_audit', 'system:manage_court_config'],
    stage_access: ['filing', 'preparation', 'scrutiny', 'defect_cure', 'scanning'],
  },
  {
    id: 'filing_officer',
    name: 'filing_officer',
    display_name: 'Filing Officer',
    permissions: ['any:view_metadata', 'any:view_case_file', 'any:case_lookup', 'filing:create'],
    stage_access: ['filing'],
  },
  {
    id: 'preparation_officer',
    name: 'preparation_officer',
    display_name: 'Preparation Officer',
    permissions: ['any:view_metadata', 'any:view_case_file', 'preparation:edit', 'preparation:submit'],
    stage_access: ['preparation'],
  },
  {
    id: 'scrutiny_officer',
    name: 'scrutiny_officer',
    display_name: 'Scrutiny Officer',
    permissions: ['any:view_metadata', 'any:view_case_file', 'scrutiny:checklist', 'scrutiny:approve', 'scrutiny:reject', 'scrutiny:note_defects', 'scrutiny:message'],
    stage_access: ['scrutiny'],
  },
  {
    id: 'defect_officer',
    name: 'defect_officer',
    display_name: 'Defect Cure Officer',
    permissions: ['any:view_metadata', 'any:view_case_file', 'defect:edit_case_file', 'defect:mark_removed', 'defect:return', 'defect:reject', 'defect:message'],
    stage_access: ['defect_cure'],
  },
  {
    id: 'scanning_officer',
    name: 'scanning_officer',
    display_name: 'Scanning Officer',
    permissions: ['any:view_metadata', 'scanning:upload_pdf', 'any:case_lookup'],
    stage_access: ['scanning'],
  },
];

export const MOCK_AUDIT: AuditEntry[] = [
  { id: 'a1', actor: 'Vyshnav Filing', actor_role: 'filing_officer', action: 'FILING_CREATED', resource_type: 'filing', resource_id: 'D-WP(C)/4688/2026', description: 'New filing created: Writ Petition (Civil)', timestamp: '2026-03-10T09:15:00Z' },
  { id: 'a2', actor: 'Vyshnav Filing', actor_role: 'filing_officer', action: 'FILING_SUBMITTED', resource_type: 'filing', resource_id: 'D-WP(C)/4688/2026', description: 'Filing submitted to CIS, diary number assigned', timestamp: '2026-03-10T09:20:00Z' },
  { id: 'a3', actor: 'Vyshnav Scanning', actor_role: 'scanning_officer', action: 'SCANNING_COMPLETED', resource_type: 'filing', resource_id: 'D-WP(C)/4688/2026', description: 'Physical documents scanned and uploaded', timestamp: '2026-03-11T10:30:00Z' },
  { id: 'a4', actor: 'Vyshnav Preparation', actor_role: 'preparation_officer', action: 'PREPARATION_STARTED', resource_type: 'filing', resource_id: 'D-WP(C)/4688/2026', description: 'Case file preparation started', timestamp: '2026-03-11T14:00:00Z' },
  { id: 'a5', actor: 'Vyshnav Preparation', actor_role: 'preparation_officer', action: 'PREPARATION_SUBMITTED', resource_type: 'filing', resource_id: 'D-WP(C)/4688/2026', description: 'Case file prepared and submitted to scrutiny', timestamp: '2026-03-11T16:45:00Z' },
  { id: 'a6', actor: 'Vyshnav Scrutiny', actor_role: 'scrutiny_officer', action: 'SCRUTINY_APPROVED', resource_type: 'filing', resource_id: 'D-WP(C)/4688/2026', description: 'Case approved for registration', timestamp: '2026-03-12T11:30:00Z' },
  { id: 'a7', actor: 'System', actor_role: 'system', action: 'CASE_REGISTERED', resource_type: 'filing', resource_id: 'D-WP(C)/4688/2026', description: 'CNR assigned: ORHC01-000688-2026', timestamp: '2026-03-12T11:31:00Z' },
  { id: 'a8', actor: 'Vyshnav Filing', actor_role: 'filing_officer', action: 'FILING_CREATED', resource_type: 'filing', resource_id: 'D-WP(C)/4689/2026', description: 'New filing created: Writ Petition (Civil)', timestamp: '2026-03-14T10:00:00Z' },
  { id: 'a9', actor: 'Vyshnav Preparation', actor_role: 'preparation_officer', action: 'PREPARATION_SUBMITTED', resource_type: 'filing', resource_id: 'D-WP(C)/4689/2026', description: 'Case file prepared and submitted to scrutiny', timestamp: '2026-03-14T15:00:00Z' },
  { id: 'a10', actor: 'Vyshnav Scrutiny', actor_role: 'scrutiny_officer', action: 'DEFECTS_NOTED', resource_type: 'filing', resource_id: 'D-WP(C)/4689/2026', description: 'Defects noted: D-07 (Affidavit), D-14 (Court fee)', timestamp: '2026-03-15T10:00:00Z' },
  { id: 'a11', actor: 'System', actor_role: 'system', action: 'SMS_SENT', resource_type: 'filing', resource_id: 'D-WP(C)/4689/2026', description: 'Defect notice SMS sent to advocate +91-9876543211', timestamp: '2026-03-15T10:01:00Z' },
  { id: 'a12', actor: 'Vyshnav Defect', actor_role: 'defect_officer', action: 'DEFECT_CURE_STARTED', resource_type: 'filing', resource_id: 'D-WP(C)/4689/2026', description: 'Defect cure process started', timestamp: '2026-03-15T11:00:00Z' },
  { id: 'a13', actor: 'Vyshnav Filing', actor_role: 'filing_officer', action: 'FILING_CREATED', resource_type: 'filing', resource_id: 'D-WP(C)/4690/2026', description: 'New filing created: Writ Petition (Civil)', timestamp: '2026-03-15T11:30:00Z' },
  { id: 'a14', actor: 'Vyshnav Preparation', actor_role: 'preparation_officer', action: 'PREPARATION_SUBMITTED', resource_type: 'filing', resource_id: 'D-WP(C)/4690/2026', description: 'Case file prepared', timestamp: '2026-03-16T09:30:00Z' },
  { id: 'a15', actor: 'Vyshnav Scrutiny', actor_role: 'scrutiny_officer', action: 'SCRUTINY_STARTED', resource_type: 'filing', resource_id: 'D-WP(C)/4690/2026', description: 'Scrutiny started', timestamp: '2026-03-17T10:00:00Z' },
  { id: 'a16', actor: 'Vyshnav Filing', actor_role: 'filing_officer', action: 'FILING_CREATED', resource_type: 'filing', resource_id: 'D-CRL(A)/0124/2026', description: 'New filing created: Criminal Appeal', timestamp: '2026-03-16T09:00:00Z' },
  { id: 'a17', actor: 'Vyshnav Scanning', actor_role: 'scanning_officer', action: 'SCANNING_COMPLETED', resource_type: 'filing', resource_id: 'D-CRL(A)/0124/2026', description: 'Documents scanned', timestamp: '2026-03-16T14:00:00Z' },
  { id: 'a18', actor: 'Vyshnav Preparation', actor_role: 'preparation_officer', action: 'PREPARATION_STARTED', resource_type: 'filing', resource_id: 'D-CRL(A)/0124/2026', description: 'Case file preparation started', timestamp: '2026-03-17T09:00:00Z' },
  { id: 'a19', actor: 'Vyshnav Filing', actor_role: 'filing_officer', action: 'FILING_CREATED', resource_type: 'filing', resource_id: 'D-CRL(A)/0125/2026', description: 'New filing created: Criminal Appeal', timestamp: '2026-03-16T14:00:00Z' },
  { id: 'a20', actor: 'Vyshnav Filing', actor_role: 'filing_officer', action: 'FILING_CREATED', resource_type: 'filing', resource_id: 'D-WPC(TAB)/0211/2026', description: 'New filing created (physical, routes to scanning)', timestamp: '2026-03-18T08:30:00Z' },
  { id: 'a21', actor: 'Vyshnav Scanning', actor_role: 'scanning_officer', action: 'SCANNING_STARTED', resource_type: 'filing', resource_id: 'D-WPC(TAB)/0211/2026', description: 'Scanning started', timestamp: '2026-03-18T10:00:00Z' },
  { id: 'a22', actor: 'Vyshnav Scrutiny', actor_role: 'scrutiny_officer', action: 'SCRUTINY_STARTED', resource_type: 'filing', resource_id: 'D-WPC(TAB)/0212/2026', description: 'Scrutiny started', timestamp: '2026-03-19T11:00:00Z' },
  { id: 'a23', actor: 'Vyshnav Scrutiny', actor_role: 'scrutiny_officer', action: 'DEFECTS_NOTED', resource_type: 'filing', resource_id: 'D-CRL(P)/0045/2026', description: 'Defect noted: D-02 (Enrollment certificate)', timestamp: '2026-03-18T14:00:00Z' },
  { id: 'a24', actor: 'Vyshnav Scrutiny', actor_role: 'scrutiny_officer', action: 'SCRUTINY_REJECTED', resource_type: 'filing', resource_id: 'D-PIL/0031/2026', description: 'Filing rejected: multiple uncured defects', timestamp: '2026-03-20T15:00:00Z' },
  { id: 'a25', actor: 'Vyshnav Registrar', actor_role: 'registrar', action: 'STAFF_CREATED', resource_type: 'staff', resource_id: 'scanning-1', description: 'Staff account created for Vyshnav Scanning', timestamp: '2026-01-01T10:00:00Z' },
  { id: 'a26', actor: 'Vyshnav Registrar', actor_role: 'registrar', action: 'SETTINGS_UPDATED', resource_type: 'settings', resource_id: 'court-config', description: 'Court name updated', timestamp: '2026-01-15T09:00:00Z' },
  { id: 'a27', actor: 'Vyshnav Registrar', actor_role: 'registrar', action: 'CHECKLIST_UPDATED', resource_type: 'checklist', resource_id: 'D-01', description: 'Defect checklist item D-01 updated', timestamp: '2026-02-01T11:00:00Z' },
  { id: 'a28', actor: 'Vyshnav Scrutiny', actor_role: 'scrutiny_officer', action: 'LOGIN', resource_type: 'auth', resource_id: 'scrutiny-1', description: 'User logged in', timestamp: '2026-03-20T09:00:00Z' },
  { id: 'a29', actor: 'Vyshnav Filing', actor_role: 'filing_officer', action: 'LOGIN', resource_type: 'auth', resource_id: 'filing-1', description: 'User logged in', timestamp: '2026-03-20T08:45:00Z' },
  { id: 'a30', actor: 'Vyshnav Preparation', actor_role: 'preparation_officer', action: 'LOGIN', resource_type: 'auth', resource_id: 'preparation-1', description: 'User logged in', timestamp: '2026-03-20T08:50:00Z' },
  { id: 'a31', actor: 'Vyshnav Defect', actor_role: 'defect_officer', action: 'LOGIN', resource_type: 'auth', resource_id: 'defect-1', description: 'User logged in', timestamp: '2026-03-20T09:05:00Z' },
  { id: 'a32', actor: 'Vyshnav Scanning', actor_role: 'scanning_officer', action: 'LOGIN', resource_type: 'auth', resource_id: 'scanning-1', description: 'User logged in', timestamp: '2026-03-20T09:10:00Z' },
  { id: 'a33', actor: 'Vyshnav Superadmin', actor_role: 'superadmin', action: 'LOGIN', resource_type: 'auth', resource_id: 'superadmin-1', description: 'Superadmin logged in', timestamp: '2026-03-20T09:15:00Z' },
  { id: 'a34', actor: 'Vyshnav Preparation', actor_role: 'preparation_officer', action: 'SECTION_ADDED', resource_type: 'filing', resource_id: 'D-CRL(A)/0124/2026', description: 'Section "Annexure A" added to case file', timestamp: '2026-03-17T11:00:00Z' },
  { id: 'a35', actor: 'Vyshnav Preparation', actor_role: 'preparation_officer', action: 'PAGES_REORDERED', resource_type: 'filing', resource_id: 'D-CRL(A)/0124/2026', description: 'Pages reordered in case file', timestamp: '2026-03-17T11:30:00Z' },
  { id: 'a36', actor: 'Vyshnav Scrutiny', actor_role: 'scrutiny_officer', action: 'SCRUTINY_SLIP_GENERATED', resource_type: 'filing', resource_id: 'D-WP(C)/4688/2026', description: 'Scrutiny slip PDF generated and downloaded', timestamp: '2026-03-12T11:28:00Z' },
  { id: 'a37', actor: 'Anaya Mishra', actor_role: 'filing_officer', action: 'FILING_CREATED', resource_type: 'filing', resource_id: 'D-CRL(A)/0125/2026', description: 'Filing intake by Ananya Mishra', timestamp: '2026-03-16T14:05:00Z' },
  { id: 'a38', actor: 'Rajan Patnaik', actor_role: 'scrutiny_officer', action: 'SCRUTINY_APPROVED', resource_type: 'filing', resource_id: 'D-CRL(A)/0124/2026', description: 'Previous version approved', timestamp: '2026-03-12T15:00:00Z' },
  { id: 'a39', actor: 'System', actor_role: 'system', action: 'DEFECT_DEADLINE_REMINDER', resource_type: 'filing', resource_id: 'D-WP(C)/4689/2026', description: 'Day 3 reminder sent to advocate', timestamp: '2026-03-18T08:00:00Z' },
  { id: 'a40', actor: 'System', actor_role: 'system', action: 'DEFECT_DEADLINE_REMINDER', resource_type: 'filing', resource_id: 'D-CRL(P)/0045/2026', description: 'Day 1 reminder sent to advocate', timestamp: '2026-03-18T08:01:00Z' },
  { id: 'a41', actor: 'Vyshnav Filing', actor_role: 'filing_officer', action: 'CASE_LOOKUP', resource_type: 'filing', resource_id: 'D-WP(C)/4688/2026', description: 'CIS case lookup performed', timestamp: '2026-03-21T10:00:00Z' },
  { id: 'a42', actor: 'Vyshnav Registrar', actor_role: 'registrar', action: 'STAFF_DEACTIVATED', resource_type: 'staff', resource_id: 'staff-10', description: 'Staff account deactivated: Sunita Jena', timestamp: '2026-03-01T14:00:00Z' },
  { id: 'a43', actor: 'Vyshnav Registrar', actor_role: 'registrar', action: 'ROLE_PERMISSIONS_UPDATED', resource_type: 'role', resource_id: 'scrutiny_officer', description: 'Scrutiny officer permissions updated', timestamp: '2026-02-15T11:00:00Z' },
  { id: 'a44', actor: 'Vyshnav Scrutiny', actor_role: 'scrutiny_officer', action: 'DEFECT_ADDED', resource_type: 'filing', resource_id: 'D-WP(C)/4689/2026', description: 'Defect D-07 added: Affidavit not sworn', timestamp: '2026-03-15T09:50:00Z' },
  { id: 'a45', actor: 'Vyshnav Scrutiny', actor_role: 'scrutiny_officer', action: 'DEFECT_ADDED', resource_type: 'filing', resource_id: 'D-WP(C)/4689/2026', description: 'Defect D-14 added: Court fee insufficient', timestamp: '2026-03-15T09:55:00Z' },
  { id: 'a46', actor: 'Vyshnav Defect', actor_role: 'defect_officer', action: 'DEFECT_RESOLVED', resource_type: 'filing', resource_id: 'D-CRL(P)/0045/2026', description: 'Defect D-02 marked as resolved', timestamp: '2026-03-19T14:00:00Z' },
  { id: 'a47', actor: 'Vyshnav Filing', actor_role: 'filing_officer', action: 'FILING_DRAFT_SAVED', resource_type: 'filing', resource_id: 'D-WPC(TAB)/0210/2026', description: 'Draft saved', timestamp: '2026-03-20T10:00:00Z' },
  { id: 'a48', actor: 'Vyshnav Scanning', actor_role: 'scanning_officer', action: 'PDF_UPLOADED', resource_type: 'filing', resource_id: 'D-WPC(TAB)/0211/2026', description: 'Scanned PDF uploaded (47 pages)', timestamp: '2026-03-18T11:30:00Z' },
  { id: 'a49', actor: 'Vyshnav Preparation', actor_role: 'preparation_officer', action: 'BOOKMARK_CREATED', resource_type: 'filing', resource_id: 'D-CRL(A)/0125/2026', description: 'Section bookmark created: Docket', timestamp: '2026-03-17T15:00:00Z' },
  { id: 'a50', actor: 'Vyshnav Preparation', actor_role: 'preparation_officer', action: 'BOOKMARK_CREATED', resource_type: 'filing', resource_id: 'D-CRL(A)/0125/2026', description: 'Section bookmark created: Appeal Memo', timestamp: '2026-03-17T15:10:00Z' },
  { id: 'a51', actor: 'Rajan Patnaik', actor_role: 'scrutiny_officer', action: 'SCRUTINY_STARTED', resource_type: 'filing', resource_id: 'D-WPC(TAB)/0212/2026', description: 'Scrutiny started by Rajan Patnaik', timestamp: '2026-03-19T11:30:00Z' },
  { id: 'a52', actor: 'Vyshnav Registrar', actor_role: 'registrar', action: 'CHECKLIST_ITEM_ADDED', resource_type: 'checklist', resource_id: 'D-32', description: 'New checklist item D-32 added', timestamp: '2026-03-20T16:00:00Z' },
  { id: 'a53', actor: 'System', actor_role: 'system', action: 'SCHEDULED_BACKUP', resource_type: 'system', resource_id: 'backup', description: 'Nightly backup completed', timestamp: '2026-03-20T02:00:00Z' },
  { id: 'a54', actor: 'Vyshnav Superadmin', actor_role: 'superadmin', action: 'SYSTEM_CONFIG_UPDATED', resource_type: 'settings', resource_id: 'court-config', description: 'Assignment mode changed to conveyor', timestamp: '2026-03-15T10:00:00Z' },
  { id: 'a55', actor: 'Vyshnav Filing', actor_role: 'filing_officer', action: 'ADVOCATE_PHONE_VERIFIED', resource_type: 'filing', resource_id: 'D-CRL(A)/0124/2026', description: 'Advocate phone number verified before filing', timestamp: '2026-03-16T08:55:00Z' },
  { id: 'a56', actor: 'Vyshnav Scrutiny', actor_role: 'scrutiny_officer', action: 'SCRUTINY_COMPLETED', resource_type: 'filing', resource_id: 'D-WP(C)/4688/2026', description: 'Scrutiny completed - approved', timestamp: '2026-03-12T11:29:00Z' },
  { id: 'a57', actor: 'System', actor_role: 'system', action: 'CNR_ASSIGNED', resource_type: 'filing', resource_id: 'D-CRL(A)/0124/2026', description: 'CNR ORHC01-000124-2026 assigned from CIS', timestamp: '2026-03-16T09:05:00Z' },
  { id: 'a58', actor: 'Vyshnav Defect', actor_role: 'defect_officer', action: 'DEFECT_CURE_OUTCOME', resource_type: 'filing', resource_id: 'D-WP(C)/4689/2026', description: 'Defects partially resolved - returned to scrutiny', timestamp: '2026-03-19T16:00:00Z' },
  { id: 'a59', actor: 'Anaya Mishra', actor_role: 'filing_officer', action: 'FILING_SUBMITTED', resource_type: 'filing', resource_id: 'D-CRL(A)/0125/2026', description: 'Filing submitted to CIS', timestamp: '2026-03-16T14:30:00Z' },
  { id: 'a60', actor: 'Vyshnav Registrar', actor_role: 'registrar', action: 'DASHBOARD_VIEWED', resource_type: 'dashboard', resource_id: 'pipeline', description: 'Pipeline dashboard viewed', timestamp: '2026-03-21T09:00:00Z' },
];

export const MOCK_CHECKLIST: ChecklistItem[] = [
  { id: 'c1', code: 'D-01', description: 'Petition/Appeal not signed by advocate', category: 'Signature', active: true },
  { id: 'c2', code: 'D-02', description: 'Advocate enrollment certificate not attached', category: 'Documents', active: true },
  { id: 'c3', code: 'D-03', description: 'Vakalatnama not attached / not properly executed', category: 'Documents', active: true },
  { id: 'c4', code: 'D-04', description: 'Memo of parties not attached', category: 'Documents', active: true },
  { id: 'c5', code: 'D-05', description: 'Impugned order/judgment not attached', category: 'Documents', active: true },
  { id: 'c6', code: 'D-06', description: 'Certified copy of impugned order not filed', category: 'Documents', active: true },
  { id: 'c7', code: 'D-07', description: 'Affidavit not sworn before a Notary / Oath Commissioner', category: 'Affidavit', active: true },
  { id: 'c8', code: 'D-08', description: 'Affidavit not duly attested', category: 'Affidavit', active: true },
  { id: 'c9', code: 'D-09', description: 'Affidavit not in prescribed format', category: 'Affidavit', active: true },
  { id: 'c10', code: 'D-10', description: 'Deponent details incomplete in affidavit', category: 'Affidavit', active: true },
  { id: 'c11', code: 'D-11', description: 'Index not attached', category: 'Index', active: true },
  { id: 'c12', code: 'D-12', description: 'Page numbers not mentioned in index', category: 'Index', active: true },
  { id: 'c13', code: 'D-13', description: 'Documents not arranged in order of index', category: 'Index', active: true },
  { id: 'c14', code: 'D-14', description: 'Court fee stamp not affixed / insufficient court fee', category: 'Court Fee', active: true },
  { id: 'c15', code: 'D-15', description: 'Court fee not of correct denomination', category: 'Court Fee', active: true },
  { id: 'c16', code: 'D-16', description: 'Process fee not paid', category: 'Court Fee', active: true },
  { id: 'c17', code: 'D-17', description: 'Certified copy of lower court order not legible', category: 'Documents', active: true },
  { id: 'c18', code: 'D-18', description: 'Translation not attached for vernacular documents', category: 'Documents', active: true },
  { id: 'c19', code: 'D-19', description: 'Limitation period not addressed / no application for condonation', category: 'Limitation', active: true },
  { id: 'c20', code: 'D-20', description: 'Condonation of delay application not filed', category: 'Limitation', active: true },
  { id: 'c21', code: 'D-21', description: 'Respondent details incomplete / incorrect', category: 'Parties', active: true },
  { id: 'c22', code: 'D-22', description: 'Address for service not mentioned', category: 'Parties', active: true },
  { id: 'c23', code: 'D-23', description: 'Inadequate copies filed', category: 'Copies', active: true },
  { id: 'c24', code: 'D-24', description: 'Documents not legible / blurred pages', category: 'Documents', active: true },
  { id: 'c25', code: 'D-25', description: 'Incomplete pleadings', category: 'Pleadings', active: true },
  { id: 'c26', code: 'D-26', description: 'Prayers not clearly stated', category: 'Pleadings', active: true },
  { id: 'c27', code: 'D-27', description: 'Previous filing number not mentioned (re-filing)', category: 'Procedural', active: true },
  { id: 'c28', code: 'D-28', description: 'Relief sought exceeds jurisdiction', category: 'Jurisdiction', active: true },
  { id: 'c29', code: 'D-29', description: 'No urgency application despite urgent relief sought', category: 'Procedural', active: true },
  { id: 'c30', code: 'D-30', description: 'Stay application fee not paid', category: 'Court Fee', active: true },
  { id: 'c31', code: 'D-31', description: 'Multiple defects not cured within stipulated time', category: 'Procedural', active: true },
];

export const MOCK_SETTINGS: CourtSettings = {
  court_name: 'Orissa High Court',
  court_short_name: 'OHC',
  case_number_prefix: 'D',
  filing_timing_mode: 'flexible',
  assignment_mode: 'conveyor',
  defect_cure_days: 5,
  timezone: 'Asia/Kolkata',
};
